name = "hacktxcloudflare"
main = "src/index.ts"
compatibility_date = "2024-11-20"

[durable_objects]
bindings = [{ name = "RACE_DO", class_name = "RaceDO" }]

[[migrations]]
tag = "v1"
new_classes = ["RaceDO"]

